name: deploy
on:
    push:
        branches:
            - master
        paths:
            ".github/workflows/*"
jobs:
    Test:
     runs-on: windows_latest
     steps:
        - name: Run the code
          run: echo "code runned"
        - name: checkout version
          uses: actions/checkout@v3
        - name: Checks dependicies
          run: npm ci
    

