name: deploy
on:
    push:
        branches:
            - main
        paths:
            ".github/workflows/*"
jobs:
    Test:
     runs-on: windows_latest
     steps:
        - name: Run the code
          run: echo "code runned"
    

